# The values here are base64 encoded.
# echo -n 'gouser' | base64  -> Z291c2Vy
# echo -n 'gopassword' | base64 -> Z29wYXNzd29yZA==
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: go-microservice-app
type: Opaque
data:
  postgres-user: Z291c2Vy
  postgres-password: Z29wYXNzd29yZA==
  postgres-db: Z29kYg==
